# app.py
import yaml
from dotenv import load_dotenv

import warnings
warnings.filterwarnings("ignore")

from utils.loader import load_and_chunk_docs
from utils.retriever_faiss import get_retriever as get_faiss_retriever
from utils.two_stage_retriever import TwoStageRetriever
from utils.reranker_cross_encoder import CrossEncoderReranker

from langchain_openai import ChatOpenAI
from langchain_google_genai import ChatGoogleGenerativeAI

load_dotenv()


# ---------------------------
# Config & LLM helpers
# ---------------------------
def load_config(path: str = "config.yaml") -> dict:
    with open(path, "r") as f:
        return yaml.safe_load(f)


def get_llm(config: dict):
    provider = config["llm"]["provider"]
    temperature = config["llm"]["temperature"]
    if provider == "openai":
        return ChatOpenAI(model=config["llm"]["model_openai"], temperature=temperature)
    elif provider == "gemini":
        return ChatGoogleGenerativeAI(model=config["llm"]["model_gemini"], temperature=temperature)
    else:
        raise ValueError("Provider must be one of: openai | gemini")

#make a context string from the top-k documents, limited to max_chars
def make_context(docs, max_chars=3000):
    text = "\n\n---\n\n".join(d.page_content.strip() for d in docs)
    return text[:max_chars]

#answer a question using the provided context and LLM
def answer_with_context(llm, context: str, question: str) -> str:
    prompt = [
        ("system", "Answer ONLY using the provided context. If the answer isn't present, say you don't know."),
        ("human", f"Context:\n{context}\n\nQuestion: {question}\nAnswer:")
    ]
    return llm.invoke(prompt).content.strip()


def brief(doc):
    title = doc.metadata.get("source", "") or doc.metadata.get("file_path", "") or ""
    snippet = doc.page_content[:100].replace("\n", " ")
    return f"{title} :: {snippet}..."


# ---------------------------
# Main
# ---------------------------
def main():
    config = load_config()
    provider = config["llm"]["provider"].upper()
    print(f"\n🚀 Active Provider: {provider}")

    # 1) Load & chunk docs (idempotent)
    chunks = load_and_chunk_docs("./data/raw/insurance_docs")

    # 2) Ensure FAISS index exists (provider-aware)
    base_retriever = get_faiss_retriever(config, chunks_if_needed=chunks)

    # 3) Build two-stage retriever (Stage1 FAISS + Stage2 Cross-Encoder)
    two_stage = TwoStageRetriever(chunks_if_needed=chunks)

    # 4) LLM for answering
    llm = get_llm(config)

    # 5) Ask
    query = input("\n🔍 Enter your question: ").strip()
    initial_k = int(config["reranking"]["initial_k"])
    final_k = int(config["reranking"]["final_k"])

    # --------------------------
    # Stage 1: Candidate Retrieval (FAISS)
    # --------------------------
    candidates = base_retriever.invoke(query)[:initial_k]
    print("\n==============================")
    print(f"✅ STAGE 1 — Candidates (k={initial_k})")
    print("==============================")
    for i, d in enumerate(candidates[:5], 1):  # show a few
        print(f"{i}. {brief(d)}")

    # --------------------------
    # Stage 2: Cross-Encoder Reranking
    # --------------------------
    reranker = CrossEncoderReranker()
    ranked_pairs = reranker.rerank(query, candidates, top_k=final_k)

    final_docs = [doc for doc, _ in ranked_pairs]

    print("\n==============================")
    print(f"✅ STAGE 2 — Reranked Top (k={final_k})")
    print("==============================")
    for i, (doc, score) in enumerate(ranked_pairs, 1):
        print(f"{i}. score={score:.4f} :: {brief(doc)}")

    # --------------------------
    # Final Answer from Reranked Context
    # --------------------------
    context = make_context(final_docs, max_chars=3000) #this is the context string made from the top-k
    #reranked documents, limited to 3000 characters
    answer = answer_with_context(llm, context, query)
    #this is the final answer generated by the LLM using the context and the query

    print("\n==============================")
    print("🧠 FINAL ANSWER (Grounded in Reranked Context)")
    print("==============================")
    print(answer)

    print("\n--- Sources (Reranked Top) ---")
    for i, d in enumerate(final_docs, 1):
        print(f"{i}. {brief(d)}")


if __name__ == "__main__":
    main()